language: python
sudo: required
python:
  - "3.6"
  - "3.7"

services:
  - docker

before_install:
  - docker pull docker.io/vmware/photon

install:
  - pip install -r requirements.txt

before_script:
  - export $PYTHONPATH=`pwd`

script:
  - ./tern report -i docker.io/vmware/photon
