# Known package listing steps for base images
debian:
  latest: jessie
  tags:
    jessie:
        shell: '/bin/bash'
        # either enter the package names as a list or a snippet to invoke either within or outside the container
        names:
          invoke:
            1:
              # Currently two types of environments are supported - host or container
              container:
                - "dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'"
          delimiter: '\n'
        # the length of this list should be the same as the names or else there will be a mismatch
        versions:
          invoke:
            1:
              container:
                - "pkgs=`dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'`"
                - "for p in $pkgs; do echo $p; dpkg -l $p | awk 'NR>5 {print $3}'; echo END; done"
          delimiter: 'END'
        licenses:
          invoke:
            1:
              container:
                - "pkgs=`dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'`"
                - "for p in $pkgs; do echo $p; cat /usr/share/doc/$package/copyright; echo END; done"
          delimiter: 'END'
        src_urls: ''
    jessie-backports:
        shell: '/bin/bash'
        names:
          invoke:
            1:
              container:
                - "dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'"
          delimiter: '\n'
        versions:
          invoke:
            1:
              container:
                - "pkgs=`dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'`"
                - "for p in $pkgs; do echo $p; dpkg -l $p | awk 'NR>5 {print $3}'; echo END; done"
          delimiter: 'END'
        licenses:
          invoke:
            1:
              container:
                - "pkgs=`dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'`"
                - "for p in $pkgs; do echo $p; cat /usr/share/doc/$package/copyright; echo END; done" 
          delimiter: 'END'
        src_urls: ''
